object Versions {
    const val GRADLE = "4.1.0"
    const val KOTLIN = "1.4.10"
    const val KTX = "1.3.2"
    const val APP_COMPAT = "1.2.0"
    const val MATERIAL = "1.2.1"
    const val CONSTRAINT_LAYOUT = "2.0.4"
    const val JUNIT = "4.13.1"
    const val EXT_JUNIT = "1.1.2"
    const val ESPRESSO = "3.3.0"
    const val HILT_ANDROID = "2.28-alpha"
    const val HILT = "1.0.0-alpha01"
    const val COROUTINES = "1.3.5"
    const val LIFECYCLE_ANDROIDX = "2.2.0"
    const val ACTIVITY_KTX = "1.1.0"
    const val LIFECYCLE_ARCH  = "1.1.1"
    const val RETROFIT ="2.6.0"
    const val OK_HTTP_LOGGER = "4.5.0"
    const val ROOM = "2.2.5"
}
